### ISSUE TITLE
Update overtime payroll detail 

### ISSUE THREAD

**Issue by uranussolutions** [uranussolutions/minhdu-fontend#129]
Có giá trị nhưng không tick, cho phép tích, hoặc bỏ tick. Nếu nhân viên chưa có thì tick vào để update thêm, còn có rồi thì bỏ tick để xóa => Nếu bỏ tick sẽ gửi lên api xóa salary theo id `{{url}}/v2/salary/{id}`
![image](https://user-images.githubusercontent.com/48413548/135311633-119baf9f-c0ef-4754-be63-f7d6df5df250.png)

![image](https://user-images.githubusercontent.com/48413548/135304226-0dff284b-6424-4afa-8109-23539ba08920.png)

**Comment by giahieu123456** [comment]
khi update salary bỏ chọn phụ cấp tăng ca , đã xóa được allowance ,
 nhưng update salary báo lỗi vì khi update không có gửi trường allowance nữa
