### ISSUE TITLE
Theem các trường trên payslip cho phù hợp với bảng lương công nhân trại chăn nuôi

### ISSUE THREAD

**Issue by uranussolutions** [uranussolutions/minhdu-fontend#147]
[LƯƠNG chăn nuôi P.Thành 4 T02-2021.xls](https://github.com/uranussolutions/minhdu-fontend/files/7262291/L.NG.chan.nuoi.P.Thanh.4.T02-2021.xls)
[T01-2021-trại chăn nuôi P.Nghĩa.xls](https://github.com/uranussolutions/minhdu-fontend/files/7262292/T01-2021-tr.i.chan.nuoi.P.Nghia.xls)

**Comment by giahieu123456** [comment]
api sẽ trả về thêm những trương nào vậy  @uranussolutions
