### ISSUE TITLE
BUG [sell]

### ISSUE THREAD

**Issue by uranussolutions** [uranussolutions/minhdu-fontend#34]
1. Fix warning khi mở tạo đơn hàng
![image](https://user-images.githubusercontent.com/48413548/128631411-47d41ec2-ceaf-4099-8c49-279f68325e8c.png)
2. No requrired
![image](https://user-images.githubusercontent.com/48413548/128631492-e64aa5a7-1be1-4838-8a2a-e267fca3fe28.png)
3. Toast "Tạo đơn hàng thành công". khi đơn hàng đc tạo thành công

**Comment by giahieu123456** [comment]
done
