### ISSUE TITLE
FIX 

### ISSUE THREAD

**Issue by uranussolutions** [uranussolutions/minhdu-fontend#40]
Theem chú thích cho cột 
![image](https://user-images.githubusercontent.com/48413548/129040092-27c16db6-8427-45e5-94a1-b850726ad30b.png)
Chỉ scroll cột ở giữa. Số lượng gà, Thống kê đơn hàng theo khách hàng, chú thích cột giá trị y giữ nguyên, không scroll theo. Tương tự những biểu đồ nào có scroll khác
![image](https://user-images.githubusercontent.com/48413548/129040204-3368c486-4185-4625-a593-ff9fbecf0745.png)
Giá trị lớn nhất phải bằng với cột cao nhất
![image](https://user-images.githubusercontent.com/48413548/129040630-aa09f074-d630-4b6c-992f-6cc709e5a1cc.png)
Custom tổng mỗi cột (soos treên hình chỉ mang tính minh hoạ)
![image](https://user-images.githubusercontent.com/48413548/129041321-c809b395-6056-4c9d-8bf5-03e077dff426.png)

**Comment by giahieu123456** [comment]
fix dc phần scoll chú thích cột thì vẫn chưa dc
