### ISSUE TITLE
Deploy

### ISSUE THREAD

**Issue by uranussolutions** [uranussolutions/minhdu-fontend#44]
- Research deploy app 2 app hr and sell ở 2 port khác nhau khi build
- Trỏ login check app của user thuộc loại nào để trỏ đến app tương ứng
- Mỗi user sẽ có chứa 1 app. dựa vào đó để phân biệt lúc login sẽ trỏ đến link tương ứng của app 
![image](https://user-images.githubusercontent.com/48413548/129474610-0000c4e6-ba83-4ac1-8caf-790f05cdf9a2.png)

**Comment by giahieu123456** [comment]
đã set port mặc định cho mỗi app , khi đăng nhập sẽ check post và sẽ gửi thêm trường app là Hr hoặc sell tùy theo app,
