### ISSUE TITLE
Sell app: Testing

### ISSUE THREAD

**Issue by uranussolutions** [uranussolutions/minhdu-fontend#52]
1. Customer

- Chạy lại 1 vòng customer check lại UI => ?
- Test lại thêm / xóa / sửa / update customer => ?
- Test lại khi đạt 1.000 - 2.000 customer data load trong bao lâu => ?
- Scroll 1.000 - 2.000 customer => ?

2. Thêm đơn hàng cho khách hàng

- Tạo lần lượt 1.000, 2.000, 3.000, 4.000, 5.000 đơn hàng cho lần lượt 1, 2, 3 ... 1.000 khách hàng
- Thanh toán ngẫu nhiên cho đơn hàng
- Xem tốc độ load tính dư nợ trong bao lâu => ?

3. Thêm đơn hàng cho chuyến xe.

- 1 xe lần lượt 100, 200 đơn

## Yêu cầu bắt buộc
1. Xe đã được giao hàng thành công 

- Không được SỬA, XÓA, THÊM đơn hàng trên xe

2. Đơn hàng đã được giao thành công

- Không được SỬA, XÓA, THÊM trên đơn hàng 

# Confirm để  bổ sung thêm các ràng buộc nếu thấy thiếu

**Comment by giahieu123456** [comment]
đơn hàng đang giao đã được thanh toán sẽ  ẩn nút hủy
