### ISSUE TITLE
test(testcase): Employee

### ISSUE THREAD

**Issue by uranussolutions** [uranussolutions/minhdu-fontend#77]
## Testlist

- [x] Loading
- [x]  Load list nhân viên
- [x]  Loadmore
- [x]  Search theo từng mục
- [x] Search kết hợp các mục với nhau
- [ ] Hiển thị lỗi khi gặp lỗi
- [ ] Report tới slack khi lỗi
- [x] Thêm nhân viên mới
- [x] Kiểm tra lỗi chính tả, Viết hoa các từ
- [x] Validate form thêm nhân viên
- [x] Validate bắt buộc nhập k được để trống khi thêm nhân viên
- [x] Xóa nhân viên, check lại xem list còn nhân viên đó không, api xóa nhân viên trong postman
- [x] Update detail nhân viên
- [ ] Thêm thành phần gia đình
- [ ] Update thành phần gia đình
- [x] Thêm bằng cấp
- [x] Update bằng cấp
- [x] Update quá trình công tác, check lại detail xem đã cập nhật lên UI detail chưa

**Comment by giahieu123456** [comment]
@uranussolutions  api add relative bị lỗi 
api report slack báo invalid_token
